import Head from 'next/head'
import supabase from "../utils/supabase"
import ConcertCard from '../components/ConcertCard'
import NewConcertForm from '../components/NewConcertForm'
import { PlusIcon } from '@heroicons/react/24/solid'
import Link from 'next/link'

export default function Home({ concerts, bands, concertBands }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="p-8">
        <h1 className="h1">
          Concert Diary
        </h1>
        <NewConcertForm bands={bands} />
        <Link href="/add-band">
          <a className="btn btn-link mt-2"><PlusIcon className="h-text" />Band hinzufügen</a>
        </Link>
        <div className="grid grid-cols-10 gap-6 mt-6">
          <div className="col-span-full">
            <h2>Konzerte</h2>
          </div>
          {concerts.map(concert => (
            <ConcertCard
              key={concert.id}
              concert={concert}
              bands={bands}
              concertBands={concertBands}
            />
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const { data: concerts, error } = await supabase.from('concerts').select('*')
  const { data: bands } = await supabase.from('bands').select('*')
  const { data: concertBands } = await supabase.from('concert_bands').select('*')

  if (error) {
    throw new Error(error)
  }

  return {
    props: {
      concerts,
      bands,
      concertBands,
    }
  }
}
