import Head from 'next/head'
import supabase from "../utils/supabase"
import Link from 'next/link'

export default function Home({ posts }) {
  console.log(supabase.auth.user())
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8">
        <h1 className="h1">
          Concert Diary
        </h1>
        <div>
          {posts.map(post => (
            <Link href={`/${post.id}`} key={post.id}>
              <a className="block underline text-blue-700">
                {post.headline}
              </a>
            </Link>
          ))}
        </div>
        <pre>{JSON.stringify(posts, null, 2)}</pre>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const { data: posts, error } = await supabase.from('posts').select('*')
  
  if (error) {
    throw new Error(error)
  }

  return {
    props: {
      posts: posts,
    }
  }
}
