import Head from 'next/head'
import supabase from "../utils/supabase"
import ConcertCard from '../components/ConcertCard'
import { PlusIcon } from '@heroicons/react/24/solid'
import Link from 'next/link'
import Navigation from '../components/navigation'

export default function Home({ concerts, bands, concertBands }) {
  return (
    <div className="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      
      <main className="max-w-2xl p-8">
        <div className="flex justify-between items-center mb-6">
          <h1 className="mb-0">
            Konzerte
          </h1>
          
          <Link href="/concerts/add">
            <a className="btn btn-primary"><PlusIcon className="h-text" />Konzert hinzufügen</a>
          </Link>
        </div>
        <div className="grid gap-4">
          {concerts.map(concert => (
            <ConcertCard
              key={concert.id}
              concert={concert}
              bands={bands}
              concertBands={concertBands}
            />
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const { data: concerts, error } = await supabase.from('concerts').select('*')
  const { data: bands } = await supabase.from('bands').select('*')
  const { data: concertBands } = await supabase.from('concert_bands').select('*')

  if (error) {
    throw new Error(error)
  }

  return {
    props: {
      concerts,
      bands,
      concertBands,
    }
  }
}
